import axios from 'axios';
import config from '../config.cjs';

const flux = async (m, Matrix) => {
  const prefix = config.PREFIX;
  const cmd = m.body.startsWith(prefix) ? m.body.slice(prefix.length).split(' ')[0].toLowerCase() : '';
  const query = m.body.slice(prefix.length + cmd.length).trim();

  if (cmd !== 'flux') return;

  if (!query) {
    return Matrix.sendMessage(m.from, { text: "❌ *Usage:* `.flux [prompt]*`" }, { quoted: m });
  }

  await Matrix.sendMessage(m.from, { react: { text: "🎨", key: m.key } });
  await Matrix.sendMessage(m.from, { text: `*🎨 Generating image for:* _${query}_...` }, { quoted: m });

  try {
    const apiUrl = `https://kaiz-apis.gleeze.com/api/fluxwebui?prompt=${encodeURIComponent(query)}`;
    const response = await axios.get(apiUrl);

    if (response.data && response.data.image) {
      const imageUrl = response.data.image;

      const contextInfo = {
        mentionedJid: [m.sender],
        forwardingScore: 999,
        isForwarded: true,
        forwardedNewsletterMessageInfo: {
          newsletterJid: '120363419090892208@newsletter',
          newsletterName: "EF-PRIME",
          serverMessageId: 143
        }
      };

      await Matrix.sendMessage(m.from, {
        image: { url: imageUrl },
        caption: `🖼️ *Prompt:* _${query}_\n\n🔗 *Image generated by EF-PRIME Flux AI ✅*`,
        contextInfo
      }, { quoted: m });

      await Matrix.sendMessage(m.from, { react: { text: "✅", key: m.key } });

    } else {
      await Matrix.sendMessage(m.from, { react: { text: "❌", key: m.key } });
      Matrix.sendMessage(m.from, { text: "❌ No image was generated. Please try again with a different prompt." }, { quoted: m });
    }

  } catch (error) {
    console.error("Flux AI Error:", error);
    await Matrix.sendMessage(m.from, { react: { text: "❌", key: m.key } });
    Matrix.sendMessage(m.from, { text: "❌ An error occurred while generating the image. Try again later." }, { quoted: m });
  }
};

export default flux
